Models/AddQuizwisequestion.cs
using System.ComponentModel.DataAnnotations;

namespace Quiz1.Models
{
    public class AddQuizwisequestion
    {
        [Required]
        public int QuizWiseQuestionsID {  get; set; }

        [Required]
        public int QuizId { get; set; }

        [Required]
        public int QuestionId { get; set; }

        [Required]
        public int UserId { get; set; }

        [Required]
        public DateTime Modified { get; set; }
    }
}

Controllers/QuizWiseQuestionController.cs
using System.Data;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using Quiz1.Models;

namespace Quiz1.Controllers
{
    public class QuizWiseQuestionController : Controller
    {
        private IConfiguration configuration;

        public QuizWiseQuestionController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult ListQuizWiseQuestions()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_QuizWiseQuestions_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return View(table);
        }

        public IActionResult AddQuizWiseQuestions()
        {
            UserDropDown();
            QuizDropDown();
            QuestionDropDown();
            return View();
        }
        public IActionResult QuizWiseQuestionsDetails()
        {
            return View();
        }

        //public IActionResult QuizwisequestionInsert(AddQuizwisequestion model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        string connectionString = this.configuration.GetConnectionString("ConnectionString");
        //        SqlConnection connection = new SqlConnection(connectionString);
        //        connection.Open();
        //        SqlCommand command = connection.CreateCommand();
        //        command.CommandType = CommandType.StoredProcedure;


        //        command.CommandText = "PR_QuizWiseQuestions_Insert";
        //        command.Parameters.Add("@QuizID", SqlDbType.Int).Value = model.QuizId;
        //        command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = model.QuestionId;
        //        command.Parameters.Add("@UserID", SqlDbType.Int).Value = model.UserId;
        //        command.Parameters.Add("@Modified", SqlDbType.DateTime).Value = model.Modified;
        //        command.ExecuteNonQuery();
        //        return RedirectToAction("ListQuizWiseQuestions");
        //    }

        //    return View("AddQuizWiseQuestions", model);
        //}

        public IActionResult AddAndEdit(AddQuizwisequestion model)
        {
            UserDropDown();
            QuizDropDown();
            QuestionDropDown();
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;

                if (model.QuizWiseQuestionsID == 0)
                {
                    command.CommandText = "PR_QuizWiseQuestions_Insert";
                }
                else
                {
                    command.CommandText = "PR_QuizWiseQuestions_UpdateByPK";
                    command.Parameters.Add("@QuizWiseQuestionsID", SqlDbType.Int).Value = model.QuizWiseQuestionsID;
                }
                command.Parameters.Add("@QuizID", SqlDbType.Int).Value = model.QuizId;
                command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = model.QuestionId;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = CommonVariable.UserID();
                command.Parameters.Add("@Modified", SqlDbType.DateTime).Value = model.Modified;
                command.ExecuteNonQuery();
                return RedirectToAction("ListQuizWiseQuestions");
            }

            return View("AddQuizWiseQuestions", model);
        }
        public IActionResult QuizWiseQuestions_From_edit(int? QuizWiseQuestionsID)
        {
            UserDropDown();
            QuizDropDown();
            QuestionDropDown();
            if (QuizWiseQuestionsID == null)
            {
                return View(new AddQuizModel { Modified = DateTime.Now });
            }
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("PR_QuizWiseQuestions_SelectByPK", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@QuizWiseQuestionsID", QuizWiseQuestionsID);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            reader.Read();
                            var model = new AddQuizwisequestion
                            {
                                QuizId = Convert.ToInt32(reader["QuizID"]),
                                QuestionId = Convert.ToInt32(reader["QuestionID"]),
                                UserId = Convert.ToInt32(reader["UserID"]),
                                Modified = Convert.ToDateTime(reader["Modified"])
                            };
                            return View(model);
                        }
                    }
                }
            }
            return View(new AddQuizwisequestion()); // Return an empty model if no data found
        }

        public IActionResult QuizWiseQuestionsDelete(int? QuizWiseQuestionsID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_QuizWiseQuestions_DeleteByPK";
                    command.Parameters.Add("@QuizWiseQuestionsID", SqlDbType.Int).Value = QuizWiseQuestionsID;


                    command.ExecuteNonQuery();
                }

                TempData["SuccessMessage"] = "QuestionLevel deleted successfully.";
                return RedirectToAction("ListQuizWiseQuestions");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the QuestionLevel: " + ex.Message;
                return RedirectToAction("ListQuizWiseQuestions");
            }
        }

        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command2 = connection.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_MST_QUIZ_DROPDWON";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<AddWiseDropDwon> Userlist = new List<AddWiseDropDwon>();
            foreach (DataRow data in dataTable2.Rows)
            {
                AddWiseDropDwon model = new AddWiseDropDwon();
                model.UserID = Convert.ToInt32(data["UserID"]);
                model.UserName = data["UserName"].ToString();
                Userlist.Add(model);
            }
            ViewBag.Userlist = Userlist;
        }

        public void QuizDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command2 = connection.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_QUIZ_dropdwon";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<AddWiseDropDwon> Quizlist = new List<AddWiseDropDwon>();
            foreach (DataRow data in dataTable2.Rows)
            {
                AddWiseDropDwon model = new AddWiseDropDwon();
                model.QuizId = Convert.ToInt32(data["QuizID"]);
                model.QuizName= data["QuizName"].ToString();
                Quizlist.Add(model);
            }
            ViewBag.Quizlist = Quizlist;
        }

        public void QuestionDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command2 = connection.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_QUESTION_dropdwon";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<AddWiseDropDwon> Questionlist = new List<AddWiseDropDwon>();
            foreach (DataRow data in dataTable2.Rows)
            {
                AddWiseDropDwon model = new AddWiseDropDwon();
                model.QuestionId = Convert.ToInt32(data["QuestionID"]);
                model.QuestionName = data["QuestionText"].ToString();
                Questionlist.Add(model);
            }

Views/QuizWiseQuestion/AddQuizWiseQuestions.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model AddQuizwisequestion
<main id="main" class="main">

    <div class="container mt-5">
        <h4 class="mb-3">Add QuizWiseQuestion </h4>
        <div class="card p-4 shadow-sm">
            <form>
                @* <input type="hidden" asp-for="@Model.QuizwisequestionId"></input> *@
                <div class="mb-3">
                    <label for="questionLevel" class="form-label fw-bold">Quiz <span class="text-danger">*</span></label>
                    <select class="form-control" asp-for="QuizId">
                        <option value="">Select Quiz</option>
                        @foreach (var quiz in ViewBag.Quizlist)
                        {
                            <option value="@quiz.QuizId">@quiz.QuizName</option>
                        }
                    </select>
                    <span class="text-danger" asp-validation-for="QuizId"></span>
                </div>

                @*  Question id *@
                <div class="mb-3">
                    <label for="Userid" class="form-label fw-bold">Question <span class="text-danger">*</span></label>
                    <select class="form-control" asp-for="QuestionId">
                        <option value="">Select Question</option>
                        @foreach (var question in ViewBag.Questionlist)
                        {
                            <option value="@question.QuestionId">@question.QuestionName</option>
                        }
                    </select>
                    <span class="text-danger" asp-validation-for="QuestionId"></span>
                </div>


                <!--  Modified Questions -->
                <div class="mb-3">
                    <label for="quizDate" class="form-label fw-bold">Modified <span class="text-danger">*</span></label>
                    <input type="date" class="form-control" id="Modified" asp-for="Modified">
                    <span class="text-danger" asp-validation-for="Modified"></span>
                </div>



                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-success" asp-controller="QuizWiseQuestion" asp-action="AddAndEdit">Save</button>
                    <button type="reset" class="btn btn-danger">Cancel</button>
                </div>
            </form>
        </div>
    </div>


</main>

Views/QuizWiseQuestion/ListQuizWiseQuestions.cshtml
@model DataTable
@using System.Data


<main id="main" class="main">

<div class="container mt-4">
    <h4 class="mb-3">Quiz Wise Questions</h4>



    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Tables</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quiz Wise Questions</li>
        </ol>
    </nav>

      

    <!-- Search Section -->
    <div class="card p-4 mb-4">
        <h5>Search</h5>
        <div class="row">
            <div class="col-md-4">
                <label class="form-label">Select Quiz</label>
                <select class="form-select">
                    <option selected disabled>Select Quiz</option>
                    <option>English Grammar Test</option>
                    <option>General Knowledge Quiz</option>
                    <option>Geography Challenge</option>
                    <option>History Test</option>
                    <option>Programming Quiz</option>
                </select>
            </div>
        </div>
        <div class="mt-3">
            <button class="btn btn-success">Search</button>
            <button class="btn btn-danger">Reset</button>
        </div>
    </div>

    <!-- Quiz List Header -->
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h5 class="mb-0">Quiz Wise Questions</h5>
            <a asp-controller="QuizWiseQuestion" asp-action="AddQuizWiseQuestions" class="btn btn-primary">Add Quiz Wise Question</a>
    </div>

    <!-- Quiz Table -->
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light">
                    <tr>
                        <th>Quiz Name</th>
                        <th>Entered Questions</th>
                        <th>User Name</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @if (Model == null || Model.Rows.Count == 0)
                    {
                        <tr>
                            <td colspan="4" class="text-center text-danger">No data available.</td>
                        </tr>
                    }
                    else
                    {
                        foreach (DataRow datarow in Model.Rows)
                        {
                            <tr>
                                <td>@datarow["QuizName"]</td>
                                <td>@datarow["QuestionText"]</td>
                                <td>@datarow["UserName"]</td>
                                <td>
                                    <a asp-controller="QuizWiseQuestion" asp-action="QuizWiseQuestionsDetails" class="btn btn-sm btn-outline-info">
                                        ℹ Details
                                    </a>
                                        <a asp-controller="QuizWiseQuestion" asp-action="QuizWiseQuestions_From_edit" asp-route-QuizWiseQuestionsID="@datarow["QuizWiseQuestionsID"]" class="btn btn-sm btn-outline-success">
                                            ✏ Edit
                                         </a>
                                    <a asp-controller="QuizWiseQuestion" asp-action="QuizWiseQuestionsDelete" asp-route-QuizWiseQuestionsID="@datarow["QuizWiseQuestionsID"]" class="btn btn-sm btn-outline-danger">
                                            ❌ Delete
                                     </a>
                                   
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

    <!-- Pagination -->
    <div class="d-flex justify-content-between mt-3">
        <span>Showing 1 to 5 of 5 entries</span>
        <nav>
            <ul class="pagination pagination-sm mb-0">
                <li class="page-item disabled"><a class="page-link">Previous</a></li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </nav>
    </div>

</div>
</main>
<script>
    function alertbox() {
      alert("Are you sure for delete data");
    }
</script>

Views/QuizWiseQuestion/QuizWiseQuestionsDetails.cshtml
<main id="main" class="main">
    <div class="container mt-4">
        <h4 class="mb-3">Quiz wise Question Details</h4>

        <div class="d-flex justify-content-between align-items-center mb-3">
            <h6>Quiz Name: <strong>English Grammar Test</strong> | Total Questions in Quiz: <strong>10</strong></h6>
            <div>
                <button class="btn btn-danger me-2">Delete Selected</button>
                <button class="btn btn-primary">Add Questions</button>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-bordered table-striped text-center">
                <thead class="table-light">
                    <tr>
                        <th><input type="checkbox"></th>
                        <th>Question</th>
                        <th>Option A</th>
                        <th>Option B</th>
                        <th>Option C</th>
                        <th>Option D</th>
                        <th>Correct Option</th>
                        <th>Marks</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><input type="checkbox"></td>
                        <td>What is the capital of France?</td>
                        <td>Berlin</td>
                        <td>Madrid</td>
                        <td>Paris</td>
                        <td>Lisbon</td>
                        <td><strong>C</strong></td>
                        <td>1</td>
                        <td><button class="btn btn-danger btn-sm action-btn">× Delete</button></td>
                    </tr>
                    <tr>
                        <td><input type="checkbox"></td>
                        <td>What is the currency of Japan?</td>
                        <td>Dollar</td>
                        <td>Yen</td>
                        <td>Peso</td>
                        <td>Rupee</td>
                        <td><strong>B</strong></td>
                        <td>1</td>
                        <td><button class="btn btn-danger btn-sm action-btn">× Delete</button></td>
                    </tr>
                    <tr>
                        <td><input type="checkbox"></td>
                        <td>Which planet is known as the Red Planet?</td>
                        <td>Earth</td>
                        <td>Mars</td>
                        <td>Jupiter</td>
                        <td>Venus</td>
                        <td><strong>B</strong></td>
                        <td>2</td>
                        <td><button class="btn btn-danger btn-sm action-btn">× Delete</button></td>
                    </tr>
                    <tr>
                        <td><input type="checkbox"></td>
                        <td>Who discovered gravity?</td>
                        <td>Newton</td>
                        <td>Einstein</td>
                        <td>Galileo</td>
                        <td>Kepler</td>
                        <td><strong>A</strong></td>
                        <td>2</td>
                        <td><button class="btn btn-danger btn-sm action-btn">× Delete</button></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

                </main>

Views/QuizWiseQuestion/QuizWiseQuestions_From_edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model AddQuizwisequestion
<main id="main" class="main">

    <div class="container mt-5">
        <h4 class="mb-3">Update QuizWiseQuestion </h4>
        <div class="card p-4 shadow-sm">
            <form asp-controller="QuizWiseQuestion" asp-action="AddAndEdit" method="post">

                <input type="hidden" asp-for="@Model.QuizWiseQuestionsID" />

                <div class="mb-3">
                    <label for="questionLevel" class="form-label fw-bold">Quiz <span class="text-danger">*</span></label>
                    <select class="form-control" asp-for="QuizId">
                        <option value="">Select QuizId</option>
                        @foreach (var quiz in ViewBag.Quizlist)
                        {
                            <option value="@quiz.QuizId">@quiz.QuizName</option>
                        }
                    </select>
                    <span class="text-danger" asp-validation-for="QuizId"></span>
                </div>

                @*  Question id *@
                <div class="mb-3">
                    <label for="Userid" class="form-label fw-bold">Question  <span class="text-danger">*</span></label>
                    <select class="form-control" asp-for="QuestionId">
                        <option value="">Select Question</option>
                        @foreach (var question in ViewBag.Questionlist)
                        {
                            <option value="@question.QuestionId">@question.QuestionName</option>
                        }
                    </select>
                    <span class="text-danger" asp-validation-for="QuestionId"></span>
                </div>
                

                <!--  Modified Questions -->
                <div class="mb-3">
                    <label for="quizDate" class="form-label fw-bold">Modified <span class="text-danger">*</span></label>
                    <input type="date" class="form-control" id="Modified" asp-for="Modified">
                    <span class="text-danger" asp-validation-for="Modified"></span>
                </div>

                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-success">Save</button>
                    <button type="reset" class="btn btn-danger">Cancel</button>
                </div>
            </form>
        </div>
    </div>


</main>